### ISSUE TITLE
Zu viele Trennzeichen 

### ISSUE THREAD

**Issue by dertuxmalwieder** [mdom/tazdegopher#1]
Moin,

gerade versehentlich festgestellt, dass ausgerechnet die taz auf Gopher ist. Muss ich die ja doch mal lesen... 

Jedenfalls: auf meinem mobilen Gopher (OnePlus 5T, Browser: DiggieDog) haben die Überschriften zu viele Trennzeichen. 

![](https://i.imgur.com/Qp3Vork.jpg)

Ob es dafür eine elegante Lösung gibt, weiß ich nicht.

**Comment by mdom** [comment]
Probier mal als Starturl [gopher://taz.de/1?wrap=50](gopher://taz.de/1?wrap=50). Hilft dir natürlich nicht, wenn taz.de von woanders verlinkt wird, und elegant ist es auch nicht.

**Comment by dertuxmalwieder** [comment]
Das kann mein mobiler Client nicht. :( Schaue ich später mal auf dem Desktop...

**Comment by mdom** [comment]
On Mon, Jul 09, 2018 at 04:11:33AM -0700, Cthulhux wrote:
> Das kann mein mobiler Client nicht. :( Schaue ich später mal auf dem Desktop... 

Dein mobiler Client nimmt keine URLs an? :)

**Comment by dertuxmalwieder** [comment]
Zumindest keine mit Fragezeichen... Oder bin ich gerade blöd?
